Feature/avis
ach-ber/IWA pull request #10
Opened 2023-10-12 08:48 UTC by ach-ber

Ajout des pages Avis

2023-10-12 09:10 UTC, TeenaNuihau reviewed
bon pour moi

2023-10-12 13:13 UTC, ocean-sicard-baux requested changes
Unable to resolve "@eva-design/eva" from "App.js"

l'appli se lance pas

je sais pas pourquoi tu as aussi supprimé ui-kitten et d'autres bibliothèques

2023-10-12 13:13 UTC, ocean-sicard-baux commented on seasonjob-app/package.json
> -    "@eva-design/eva": "^2.2.0",
?

2023-10-12 13:13 UTC, ocean-sicard-baux commented on seasonjob-app/package.json
> -    "@ui-kitten/components": "^5.3.1",
?

2023-10-15 09:27 UTC, ocean-sicard-baux approved these changes

2023-10-15 09:27 UTC, merged